// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OMV7p6JMkQQBmG5pF504JC-FOTnu-o4',
    appId: '1:591013084324:web:f074c7e9612ddf72c1fa31',
    messagingSenderId: '591013084324',
    projectId: 'pos-application-90299',
    authDomain: 'pos-application-90299.firebaseapp.com',
    storageBucket: 'pos-application-90299.firebasestorage.app',
    measurementId: 'G-1K95VBX55L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6H8IA1Xgj0VAEIIleKNT_9Bl2Dk4cXw',
    appId: '1:591013084324:android:618b0e28b5ee532ec1fa31',
    messagingSenderId: '591013084324',
    projectId: 'pos-application-90299',
    storageBucket: 'pos-application-90299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTQYBV1ps-wtXpbis0ycuNZZt7jDFoxQ',
    appId: '1:591013084324:ios:885975c040364765c1fa31',
    messagingSenderId: '591013084324',
    projectId: 'pos-application-90299',
    storageBucket: 'pos-application-90299.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjTQYBV1ps-wtXpbis0ycuNZZt7jDFoxQ',
    appId: '1:591013084324:ios:885975c040364765c1fa31',
    messagingSenderId: '591013084324',
    projectId: 'pos-application-90299',
    storageBucket: 'pos-application-90299.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );
}
