// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// This app is scoped to iOS and Android only (phone + tablet/iPad) —
// see README "Prerequisites". macOS/web/windows/linux are deliberately
// unconfigured rather than left as dead FirebaseOptions blocks; re-run
// `flutterfire configure` if a platform is ever added back.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not configured for web — this app '
        'targets iOS and Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform — this app targets iOS and Android only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6H8IA1Xgj0VAEIIleKNT_9Bl2Dk4cXw',
    appId: '1:591013084324:android:618b0e28b5ee532ec1fa31',
    messagingSenderId: '591013084324',
    projectId: 'pos-application-90299',
    storageBucket: 'pos-application-90299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTQYBV1ps-wtXpbis0ycuNZZt7jDFoxQ',
    appId: '1:591013084324:ios:885975c040364765c1fa31',
    messagingSenderId: '591013084324',
    projectId: 'pos-application-90299',
    storageBucket: 'pos-application-90299.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );
}
